# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    machine: 
      image: ubuntu-2004:202101-01
    working_directory: ~/amazon-rts-backend
    steps:
      - checkout

      - add_ssh_keys: # add private SSH key from CircleCI account based on fingerprint
          fingerprints:
            - "c3:d7:b5:3f:f9:3a:cd:60:f7:40:1a:a7:b6:5c:8d:bf"
      - run:
          name: Deploy dev
          command: |
            if [[ "${CIRCLE_BRANCH}" == "development" ]]
            then
            ssh ubuntu@18.237.21.143 bash ./cicd-script.bash
            fi
      - run:
          name: Deploy Master
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]
            then
            ssh ubuntu@18.237.21.143 bash ./cicd-script.bash
            fi
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.17

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: echo "Everything good!"
workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build